### PR TITLE
Create readme

### PR DESCRIPTION
**Pull request by hebronh**
Goal: allow users to select wind type and wind origin

### CODE REVIEW

**Comment by yashaswini-slu** [comment]
Can you update how you are going to proceed with design.

**Comment by kate-holdener** [comment]
@hebronh Please avoid adding files that are specific to you only. We use GitHub issues to keep track of who is doing what work, we don't want to do that in the repo itself. Since no work has been done on this, you should convert this pull request to a draft.

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Can you delete the readme file and the folder with your name

**Review by yashaswini-slu — COMMENTED** [review]
When there is no new library or dependency added you should never commit package.json file

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Design of the status is not appropriate

**Comment by hebronh** [comment]
I apologize, what was the error with design status?

**Comment by hebronh** [comment]
How can I edit this?

**Pull request closed without merging**
