### PR TITLE
sUAV type selection menu

### PR DESCRIPTION
**Pull request by kalyus**

### CODE REVIEW

**Comment by kate-holdener** [comment]
@kalyus this should be a draft pull request, convert it to draft until you are ready with your changes.

**Comment by ankyAgrawal** [comment]
[UI : Allow users to select sUAS type](https://trello.com/c/YBcbUVm3/12-ui-allow-users-to-select-suas-type)

**Comment by kate-holdener** [comment]
>  [UI : Allow users to select sUAS type](https://trello.com/c/YBcbUVm3/12-ui-allow-users-to-select-suas-type)

This Trello board is private, so developers would need access.

**Comment by ankyAgrawal** [comment]
> >  [UI : Allow users to select sUAS type](https://trello.com/c/YBcbUVm3/12-ui-allow-users-to-select-suas-type)
> 
> This Trello board is private, so developers would need access.

Here is the link to access it : 
https://trello.com/invite/b/uek3I62W/ATTI7cdba2948038a2fac8754bf9b132764bFFE599E7/devboard-droneworld

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Add the drone types in an array. Similar to flight path.

**Review by yashaswini-slu — COMMENTED** [review]
Add the drone types in an array. Similar to flight path.

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Set Drone type "Multi-rotor" as default

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Can you delete the readme file and the folder with your name

**Review by yashaswini-slu — APPROVED** [review]
Drone Type design is approved

**Pull request merged**
