### PR TITLE
Issue 3

### PR DESCRIPTION
**Pull request by sr259**
Implemented a drop-down menu for both the wind type and the wind origin. Some things to note, since there was little information given based on the wind origin, some editing needs to be done to give the menu the correct values. Also, there is an issue with the spacing that needs to be resolved.

### CODE REVIEW

**Comment by sr259** [comment]
Changed it so that the wind origin dropdown menu changes are commented out. You can utilize them on a different ticket

**Review by yashaswini-slu — CHANGES_REQUESTED** [review]
Do not set the value to envConf, its not yet implemented in api. Just comment out those lines for this issue, its a different issue.

**Comment by sr259** [comment]
Ok, I commented the code out and I also changed the spacing so everything fit better

**Review by yashaswini-slu — COMMENTED** [review]
Set Wind type "Constant Wind" as default, remove the option "None"

**Review by yashaswini-slu — APPROVED** [review]
Wind Type drop-down design is approved.

**Pull request merged**
